use_frameworks!

platform :ios, '9.0'

target 'INSParseUI_Example' do
  pod 'INSParseUI', :path => '../'

  target 'INSParseUI_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
