install! 'cocoapods',
  :preserve_pod_file_structure => true

use_frameworks!

platform :ios, '13.0'

target 'INSParseUI_Example' do
  pod 'INSParseUI', :path => '../'
  pod 'SwiftTheme'

  target 'INSParseUI_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
